source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.2.7.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'puma'
gem 'haml-rails', '~> 0.9'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'breadcrumbs_on_rails'
gem 'kaminari'
gem 'jbuilder', '~> 2.0'
gem 'therubyracer'
gem 'responders'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails', '~> 3.5'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'awesome_print', '1.6.1'
  gem 'factory_girl_rails'
  gem 'faker'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'better_errors'
end

group :test do
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
  gem 'codecov', require: false
end
