source 'https://rubygems.org'
ruby "2.0.0"

gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'simple_form', '~> 3.2', '>= 3.2.1'
gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'devise', '~> 3.5', '>= 3.5.10'
gem 'will_paginate', '~> 3.1'
gem 'validates_cpf_cnpj'
gem 'maskedinput-rails'

group :development, :test do
  gem 'byebug'
  gem 'factory_girl_rails', '~> 4.7'
  gem 'faker', '~> 1.6', '>= 1.6.3'
  gem 'pry-rails', '~> 0.3.4'
  gem 'rspec-rails', '~> 3.4', '>= 3.4.2'
  gem 'simplecov', '~> 0.11.2', require: false
  gem 'database_cleaner', '~> 1.5', '>= 1.5.3'
  gem 'shoulda-matchers', '~> 3.1', '>= 3.1.1', require: false
  gem 'capybara', '~> 2.7', '>= 2.7.1'
  gem 'selenium-webdriver', '~> 2.53', '>= 2.53.1'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
