source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'dotenv-rails', require: 'dotenv/rails-now'
gem 'responders'
gem 'enumerate_it'
gem 'ar-uuid'
gem 'jsonapi-serializers'
gem 'rack-cors', require: 'rack/cors'

group :development, :test do
  gem 'byebug'
  gem 'faker'
  gem 'factory_girl_rails'
end

group :development do
  gem 'meta_request'
  gem 'better_errors'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'guard'
  gem 'guard-rspec', require: false
end

group :test do
  gem 'database_cleaner'
  gem 'rspec-rails', '~> 3.4'
  gem 'capybara'
  gem 'brakeman', require: false
end
