require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CoursesStudentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CoursesStudent. As you add validations to CoursesStudent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoursesStudentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all courses_students as @courses_students" do
      courses_student = CoursesStudent.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:courses_students)).to eq([courses_student])
    end
  end

  describe "GET #show" do
    it "assigns the requested courses_student as @courses_student" do
      courses_student = CoursesStudent.create! valid_attributes
      get :show, {:id => courses_student.to_param}, valid_session
      expect(assigns(:courses_student)).to eq(courses_student)
    end
  end

  describe "GET #new" do
    it "assigns a new courses_student as @courses_student" do
      get :new, {}, valid_session
      expect(assigns(:courses_student)).to be_a_new(CoursesStudent)
    end
  end

  describe "GET #edit" do
    it "assigns the requested courses_student as @courses_student" do
      courses_student = CoursesStudent.create! valid_attributes
      get :edit, {:id => courses_student.to_param}, valid_session
      expect(assigns(:courses_student)).to eq(courses_student)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CoursesStudent" do
        expect {
          post :create, {:courses_student => valid_attributes}, valid_session
        }.to change(CoursesStudent, :count).by(1)
      end

      it "assigns a newly created courses_student as @courses_student" do
        post :create, {:courses_student => valid_attributes}, valid_session
        expect(assigns(:courses_student)).to be_a(CoursesStudent)
        expect(assigns(:courses_student)).to be_persisted
      end

      it "redirects to the created courses_student" do
        post :create, {:courses_student => valid_attributes}, valid_session
        expect(response).to redirect_to(CoursesStudent.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved courses_student as @courses_student" do
        post :create, {:courses_student => invalid_attributes}, valid_session
        expect(assigns(:courses_student)).to be_a_new(CoursesStudent)
      end

      it "re-renders the 'new' template" do
        post :create, {:courses_student => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested courses_student" do
        courses_student = CoursesStudent.create! valid_attributes
        put :update, {:id => courses_student.to_param, :courses_student => new_attributes}, valid_session
        courses_student.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested courses_student as @courses_student" do
        courses_student = CoursesStudent.create! valid_attributes
        put :update, {:id => courses_student.to_param, :courses_student => valid_attributes}, valid_session
        expect(assigns(:courses_student)).to eq(courses_student)
      end

      it "redirects to the courses_student" do
        courses_student = CoursesStudent.create! valid_attributes
        put :update, {:id => courses_student.to_param, :courses_student => valid_attributes}, valid_session
        expect(response).to redirect_to(courses_student)
      end
    end

    context "with invalid params" do
      it "assigns the courses_student as @courses_student" do
        courses_student = CoursesStudent.create! valid_attributes
        put :update, {:id => courses_student.to_param, :courses_student => invalid_attributes}, valid_session
        expect(assigns(:courses_student)).to eq(courses_student)
      end

      it "re-renders the 'edit' template" do
        courses_student = CoursesStudent.create! valid_attributes
        put :update, {:id => courses_student.to_param, :courses_student => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested courses_student" do
      courses_student = CoursesStudent.create! valid_attributes
      expect {
        delete :destroy, {:id => courses_student.to_param}, valid_session
      }.to change(CoursesStudent, :count).by(-1)
    end

    it "redirects to the courses_students list" do
      courses_student = CoursesStudent.create! valid_attributes
      delete :destroy, {:id => courses_student.to_param}, valid_session
      expect(response).to redirect_to(courses_students_url)
    end
  end

end
