# frozen_string_literal: true

class TbCurso < ActiveRecord::Base
  # main config ...............................................................
  audited
  self.table_name = 'edools.tb_cursos'

  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :tb_escola, class_name: 'TbEscola'

  # validations ...............................................................
  validates_presence_of :titulo, :duracao, :qtd_alunos_ativos, :preco
  validates_length_of :titulo, maximum: 255
  validates_numericality_of :duracao, :qtd_alunos_ativos

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
